In [9]:
import pandas as pd


df=pd.read_csv("resourse/movie_top100.csv")
df.head(10)#显示前10行数据
df.tail(10)#显示后10行数据
df.describe()#显示数据的统计信息
df["电影名"]#选择列
df[["电影名","导演","上映时间","评分"]]#选择多列
df.iloc[0:5]#基于行号选择行
df.loc[0:5]#基于行索引号选择行和列

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,宣传语,简介
0,安昂传奇：最后的气宗,(2026),2026-07-24 (US),"动画,动作,冒险,奇幻",1h 39m,92,英语,劳伦·蒙哥马利,Kenneth Lin,The legacy reawakens.,派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,约翰·惠廷顿,Adam J. Karp,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
2,不期而遇的姐妹,(2026),2026-03-12 (MX),"喜剧,爱情",1h 25m,89,西班牙语,Carlos Tobías Gambia,Carmen Castro,简介,两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。
3,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,近藤光,NaN,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
4,肖申克的救赎,(1994),2026-08-28 (CN),"剧情,犯罪",2h 22m,87,英语,斯蒂芬·金,NaN,恐惧会将你囚禁，希望则能让你获得自由。,安迪·杜佛兰因被错判谋杀妻子及其情人，被判处两项无期徒刑，送入缅因州的肖申克监狱服刑。在残酷...
5,教父,(1972),1972-03-24 (US),"剧情,犯罪",2h 55m,87,英语,马里奥·普佐,NaN,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...

In [14]:
#条件过滤
df[df["评分"]>8.5]
df[df["类型"].isin(["动画","喜剧"])]
df[df["评分"].between(80,90)]#包含80和90，也可以自己设置那边包含
df[(df["评分"]>8.5) & (df["类型"].isin(["动画","喜剧"])) & (df["评分"].between(80,90))]#多条件过滤
df[(df["评分"]>8.5) | (df["类型"].isin(["动画","喜剧"])) | (df["评分"].between(80,90))]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,宣传语,简介
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,约翰·惠廷顿,Adam J. Karp,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
2,不期而遇的姐妹,(2026),2026-03-12 (MX),"喜剧,爱情",1h 25m,89,西班牙语,Carlos Tobías Gambia,Carmen Castro,简介,两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。
3,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,近藤光,NaN,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
4,肖申克的救赎,(1994),2026-08-28 (CN),"剧情,犯罪",2h 22m,87,英语,斯蒂芬·金,NaN,恐惧会将你囚禁，希望则能让你获得自由。,安迪·杜佛兰因被错判谋杀妻子及其情人，被判处两项无期徒刑，送入缅因州的肖申克监狱服刑。在残酷...
5,教父,(1972),1972-03-24 (US),"剧情,犯罪",2h 55m,87,英语,马里奥·普佐,NaN,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...
...,...,...,...,...,...,...,...,...,...,...,...
95,现代启示录,(1979),1979-05-19 (CN),"剧情,战争",3h 22m,83,英语,约瑟夫·康拉德,NaN,这就是终点...,越战期间，威拉德上尉受命执行一项危险任务，深入柬埔寨刺杀一位脱离建制的叛变上校——此人已在当...
96,玩具总动员5,(2026),2026-06-19 (CN),"动画,家庭,喜剧,冒险",1h 42m,83,英语,Rita Hsiao,乔尔·科恩,大战开启,胡迪、巴斯光年、翠斯等“元老级”玩具将跟随小主人邦妮的成长脚步，共同迎接数字时代下的全新挑战...
97,萤火之森,(2011),2011-09-17 (JP),"爱情,动画,奇幻",44m,83,日语,NaN,NaN,我已经等不到夏天了,某年夏天，6岁小女孩竹川萤来到爷爷家度假，她闯进了传说住满妖怪的山神森林。正当她因为迷路而焦...
98,从前有个工作室,(2023),2023-11-24 (CN),"动画,家庭,奇幻,剧情,喜剧",9m,83,英语,Dan Abraham,NaN,100 years of Disney magic comes together.,短片为迪士尼成立满100周年的纪念作品，导演崔伦特·柯瑞和丹·亚伯拉罕花了大约八个月时间构思...
99,黑客帝国,(1999),2000-01-14 (CN),"动作,科幻",2h 16m,83,英语,拉娜·沃卓斯基,NaN,欢迎来到现实世界,不久的将来，网络黑客尼奥对这个看似正常的现实世界产生了怀疑。他结识了黑客崔妮蒂，并见到了黑客...

In [16]:
#数据清洗
df.dropna()#删除有空值的行，返回新的DataFrame，原DataFrame不变
df.dropna(axis=1)#删除有空值的列
df.drop(0)#删除指定索引行
df.fillna(0)#用0填充空值
df.replace(0,1)#用1替换0
df.duplicated()#检测重复行
df.drop_duplicates()#删除重复行（整行重复才删除）
df.drop_duplicates(subset=["电影名"],keep="first")#删除重复行，subset指定根据哪一列进行去重，keep指定保留哪个，first表示保留第一个，last表示保留最后一个，False表示不保留

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [17]:
#数据排序
df.sort_values(by="评分",ascending=False)#按评分降序排序
df.sort_values(by="评分",ascending=True)#按评分升序排序
df.sort_values(by=["评分","上映时间"],ascending=[False,True])#按评分降序排序，如果评分相同则按上映时间升序排序

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,宣传语,简介
0,安昂传奇：最后的气宗,(2026),2026-07-24 (US),"动画,动作,冒险,奇幻",1h 39m,92,英语,劳伦·蒙哥马利,Kenneth Lin,The legacy reawakens.,派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...
2,不期而遇的姐妹,(2026),2026-03-12 (MX),"喜剧,爱情",1h 25m,89,西班牙语,Carlos Tobías Gambia,Carmen Castro,简介,两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,约翰·惠廷顿,Adam J. Karp,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
3,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,近藤光,NaN,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
5,教父,(1972),1972-03-24 (US),"剧情,犯罪",2h 55m,87,英语,马里奥·普佐,NaN,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...
...,...,...,...,...,...,...,...,...,...,...,...
78,死亡诗社,(1989),2026-04-17 (CN),剧情,2h 8m,83,英语,托马斯·舒尔曼,NaN,他是他们的灵感源泉。他让他们的生命变得非凡。,威尔顿预备学院以其沉稳凝重的教学风格和较高的升学率闻名，作为其毕业班的学生，理想就是升入名校...
88,惩罚者：最后一击,(2026),2026-05-12 (US),"动作,剧情,犯罪",51m,83,英语,杰瑞·康威,乔·博恩瑟,Hey Frank.,失去家人多年后，弗兰克·卡塞尔依然被过去的创伤与幻象困扰，试图远离曾经作为“惩罚者”的暴力人...
96,玩具总动员5,(2026),2026-06-19 (CN),"动画,家庭,喜剧,冒险",1h 42m,83,英语,Rita Hsiao,乔尔·科恩,大战开启,胡迪、巴斯光年、翠斯等“元老级”玩具将跟随小主人邦妮的成长脚步，共同迎接数字时代下的全新挑战...
60,真爱留声,(2026),2026-06-20 (US),"爱情,喜剧,剧情",1h 59m,83,英语,NaN,NaN,Sometimes the universe leaves you a message.,年轻女子给已故姐姐发送的搞笑自白语音留言无意中被转给了陌生人，而这个陌生人竟隔着遥远的距离爱...
64,加百列的地狱：第三部,(2020),NaN,NaN,NaN,83,英语,Sylvain Reynard,NaN,简介,一个黑暗的人带着恶意从茱莉亚的过去回来了。加布里埃尔有他需要分享的秘密，但担心如果他这样做，...

In [19]:
#数据分组
df.groupby("语言")["评分"].mean()
df.groupby("语言")["评分"].max()
df.groupby("语言")["评分"].min()
df.groupby("语言")["评分"].sum()
df.groupby("语言")["评分"].count()

语言
-       84.666667
印地语     85.000000
意大利语    83.666667
日语      84.000000
朝鲜语     83.600000
法语      83.250000
英语      84.327273
荷兰语     86.000000
葡萄牙语    84.000000
西班牙语    84.166667
Name: 评分, dtype: float64